name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: 23-alpine3.20

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file RetroSMD.Server/Dockerfile --tag my-image-name:$(date +%s)
